import './globals.css'
import { Inter } from 'next/font/google'
import Header from '@/components/Header'
import Footer from '@/components/Footer'
import FixedButton from '@/components/FixedButton'
import Providers from "@/utils/provider";

import { QueryClient, QueryClientProvider } from "@tanstack/react-query";


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="en">
      <body className={inter.className}>
      
        <Header/>
        <Providers>{children}</Providers>
        <Footer/>
        <FixedButton/>
        </body>
    </html>
  )
}
